<div class="clearfix"></div>
<!-- <div class="navbar-fixed-bottom"> -->
    <div class="col-md-12 text-center" id="footer">
            <?php echo Html::img('creative_commons/by.png', 'Atribución'), Html::img('creative_commons/nc.png', 'NoComercial'), Html::img('creative_commons/sa.png', 'CompartirIgual'); ?>
        <p>
            <a href="http://www.icter.us">Desarrollado por Icter.us<br>2013 - 2014</a>
        </p>
    </div>
<!-- </div> -->