    <div class="navbar navbar-fixed-top header">
        <div class="col-md-12" id="col-collapse1">
              <div class="navbar-header">
                <a href="#" class="navbar-brand"><?php echo Html::img('logo_es.png'); ?></a>
              </div>
              <!--
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="fa fa-bars"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbar-collapse1">
                <ul class="nav navbar-nav navbar-right">
                   <li><a href="#"><i class="fa fa-bell"></i> Notificaciones <span class="badge">2</span></a></li>
                   <li><a href="#"><i class="fa fa-user"></i> Usuario</a></li>
                </ul>
              </div>
             -->
          </div>
    </div>