    <div class="navbar navbar-fixed-top header">
        <div class="col-md-12" id="col-collapse1">
            <div class="navbar-header">

            <a href="#" class="navbar-brand"><?php echo Html::img('logo_es.png'); ?></a>

            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse1">
              <ul class="nav navbar-nav navbar-right">
                 <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i></a>
                    <ul class="dropdown-menu">
                      <li><a href="#"><span class="badge pull-right">40</span>Link</a></li>
                      <li><a href="#"><span class="badge pull-right">2</span>Link</a></li>
                      <li><a href="#"><span class="badge pull-right">0</span>Link</a></li>
                      <li><a href="#"><span class="label label-info pull-right">1</span>Link</a></li>
                      <li><a href="#"><span class="badge pull-right">13</span>Link</a></li>
                    </ul>
                 </li>

                 <li><a href="#" id="btnToggle"><i class="fa fa-th"></i></a></li>
                 <li><a href="#"><i class="fa fa-user"></i></a></li>

               </ul>
            </div>
         </div>
    </div>
    <div class="navbar navbar-default" id="subnav">
      <div class="col-md-12">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>

        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav" id="navbar-collapse2">
            <li class="active"><a href="#">2014</a></li>
            <li><a href="#">2013</a></li>
           </ul>
        </div>
       </div>
    </div>