    <div class="navbar navbar-default" id="subnav">
        <button type="button" class="navbar-toggle" data-toggle="collapse"  data-target="#navbar-collapse2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      <div class="col-md-12">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav" id="navbar-collapse2">
            <?php foreach ($anos as $album): ?>
                <?php if ($actual == $album->year): $idx = $album->id; ?>
            <li class="active"><a href="#"><?php echo $album->year; ?></a></li>
                <?php else: ?>
            <li><a href="#"><?php echo $album->year; ?></a></li>
                <?php endif; endforeach; ?>
           </ul>
        </div>
       </div>
    </div>
    <div class="container" id="main">
        <?php View::content(); ?>
        <div class="row">
            <div class="col-md-6">
                <div class="well">
                    <h4>Subir Foto</h4>
                    <div class="panel-body">
                        <?php echo Form::openMultipart('subir/', 'post', 'class="form-horizontal"'); ?>
                            <div class="row">
                                <div class="col-xs-12">
                                    <?php echo Form::hidden('album_id', NULL, $idx),Form::file('file', 'class="filestyle" data-buttonText="Seleccione Foto" data-iconName="fa fa-inbox" data-size="md"'); ?>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-xs-12 text-right">
                                    <button type="submit" name="submit" class="btn btn-success"><i class="fa fa-upload"></i> Subir</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <?php echo Tag::js('bootstrap-filestyle.min'); ?>
                </div>
            </div>

            <div class="col-md-6 col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>#DiaUniformeScouts</h4>
                    </div>
                    <div class="panel-body">
                        <blockquote>
                            <?php echo Html::img('BadenPowell.gif', 'Baden Powell (1857-1941)', 'class="img-circle pull-right"') ?>
                            <p>La indumentaria Scout, por su uniforme, constituye un lazo más de hermandad entre los muchachos de todo el mundo.</p>
                            <footer>
                                Baden Powell (1857-1941)
                            </footer>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>

        <div id="gallery">
            <div class="row">
                <?php $i = 0; foreach ($photos->items as $photo): ?>

                <div class="col-md-4">
                    <div class="panel panel-default photo">
                        <div class="panel-thumbnail">
                            <?php echo Html::img('upload/'.$photo->name, 'Null', ' class="img-responsive"') ?>

                        </div>
                        <div class="panel-body">
                            <p><?php echo $photo->created_at; ?></p>
                        </div>
                    </div>
                </div>

            <?php $i++; if (($i % 3) == 0): ?>
            </div><div class="row">
            <?php endif; ?>

            <?php endforeach; ?>

            </div>
        </div>

        <?php if ( $photos->count > 6 ): ?>
        <div class="row">
            <div class="col-md-12" id="load">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <?php echo Html::link('paginar/', '<i class="fa fa-angle-double-down"></i> Ver más', 'id="siguiente"'); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>

     <script id="items" type="text/x-jquery-tmpl">
            <div class="col-md-4">
                <div class="panel panel-default photo">
                    <div class="panel-thumbnail">
                        <img src="<?php echo PUBLIC_PATH.'img/upload/'; ?>${name}" alt="Null" class="img-responsive">
                    </div>
                    <div class="panel-body">
                        <p>${created_at}</p>
                    </div>
                </div>
            </div>
    </script>

    <?php echo Tag::js('jquery.tmpl.min'); ?>
    <script type="text/javascript">
        $(function(){
            var page = 1;
            var actual = <?php echo $actual; ?>;
            var text = $('#siguiente').html();
            $('#siguiente').on('click', function(event){
                event.preventDefault();
                var link = this.href;
                page++;
                var url = link+page+'/'+actual;
                var loading = '<i class="fa fa-spinner fa-spin"></i> Cargando...';

                $('#siguiente').html(loading);
                $('#gallery').append('<div class="row">');
                $.getJSON(
                    url,
                    null,
                    function(data){
                        $('#items').tmpl(data.items).appendTo('#gallery');
                        $('#gallery').append('</div>');
                        $('#siguiente').html(text);
                    }
                ).fail(function(){
                    $('#load').remove();
                });

            });
            /*if(navigator.userAgent = (/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(navigator.userAgent.toLowerCase()))){
                return True
            } else {
                $('.photo').find('.panel-body').hide();
                $('.photo')
                .mouseover(function(event) {
                    //$(this).find('.panel-body').show('slow');
                    $(this).animate({ height: '+=45px' }, 2000, 'linear', function(){
                        $(this).find('.panel-body').show('slow');
                    });
                })
                .mouseout(function(event) {
                    $(this).find('.panel-body').hide();
                    $(this).stop().animate({ height: '360px' }, 2000);
                });
            }*/
        });
    </script>