<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="<?php echo APP_CHARSET ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes">

        <title><?php echo $title; ?></title>

        <!-- <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"> -->
        <?php Tag::css('bootstrap.min'); // Bootstrap 3.1.0 ?>
        <?php Tag::css('font-awesome.min'); // Font Awesome 4.0.3 ?>
        <?php Tag::css('theme'); ?>
        <?php echo Html::includeCss() ?>

        <!-- <script  type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> -->
        <!-- <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> -->
        <?php echo Tag::js('jquery.min'); // jQuery 1.10.2?>
        <?php echo Tag::js('bootstrap.min'); ?>

        <!--Load the AJAX API-->
        <!-- <script type="text/javascript" src="https://www.google.com/jsapi" async></script> -->

    </head>
    <body>

        <?php View::partial('nav'); ?>


            <?php View::content(); ?>
        </div>

        <?php View::partial('footer'); ?>

</body>
</html>
