    <div class="navbar navbar-default" id="subnav">
      <div class="col-md-12">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav" id="navbar-collapse2">
            <li class="active"><a href="#">2014</a></li>
           </ul>
        </div>
       </div>
    </div>
    <div class="container" id="main">
        <?php View::content(); ?>
        <div class="row">
            <?php foreach ($list as $photo): ?>
            <div class="col-md-12">
                <?php echo Html::img("upload/".$photo->album_id."/".$photo->name, 'Null', ' class="img-responsive"') ?>
                <?php echo Html::link('aprobar/aprobado/'.$photo->id, 'Aprobado'); ?>
            </div>
            <?php endforeach; ?>
        </div>
    </div>